### PR TITLE
feat: enable gettext supports

### PR DESCRIPTION
**Pull request by snowyu**
See Also: https://github.com/paradust7/minetest/pull/1

### CODE REVIEW

**Comment by paradust7** [comment]
How is `-sASYNCIFY` related? I recall disabling gettext because it was crashing. Does this fix that somehow?

**Comment by paradust7** [comment]
Ah, I think I understand, after reading the commit on the other repo. I think it would be better to detect/set the language in Javascript before the code even starts, so that asyncify isn't needed. I'll make that adjustment and integrate it in. Thanks for the contribution!

**Comment by snowyu** [comment]
> How is -sASYNCIFY related? I recall disabling gettext because it was crashing. Does this fix that somehow?

I use ASYNCIFY for tauri only porvides async function interface.

Yes, it's fixed for giving the lang to minetest.

**Comment by paradust7** [comment]
@snowyu  I have incorporated a language selector into the next version of the site, previewed here:

https://minetest.dustlabs.io/dev/beta/

It should be live in a day or two.

**Pull request closed without merging**
