### PR TITLE
add Dockerfile

### PR DESCRIPTION
**Pull request by BuckarooBanzay**
I'm in the progress of adding a `Dockerfile` to build the whole thing in a container
Let me know if you even want that or have issues with it

## TODO
* [x] emscripten installation
* [ ] working emscripten build
* [ ] nginx container output with built assets

## Open issues
* [ ] websocket proxy?

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
It is currently stuck on this:
```
[ 55%] Building CXX object src/CMakeFiles/minetest.dir/network/clientopcodes.cpp.o
In file included from /data/minetest/src/network/address.cpp:36:
In file included from /data/install/include/emsocket.h:40:
In file included from /emsdk-main/upstream/emscripten/system/include/emscripten/threading.h:14:
In file included from /emsdk-main/upstream/emscripten/system/include/emscripten/html5.h:13:
In file included from /emsdk-main/upstream/emscripten/system/include/emscripten/emscripten.h:28:
/emsdk-main/upstream/emscripten/system/include/emscripten/version.h:8:2: error: "Including files directly from the emscripten source tree is not supported.  Please use the cache/sysroot/include directory".
#error "Including files directly from the emscripten source tree is not supported.  Please use the cache/sysroot/include directory".
 ^
1 error generated.
em++: error: '/emsdk-main/upstream/bin/clang++ -target wasm32-unknown-emscripten -D__EMSCRIPTEN_SHARED_MEMORY__=1 -DEMSCRIPTEN -D__EMSCRIPTEN_major__=3 -D__EMSCRIPTEN_minor__=1 -D__EMSCRIPTEN_tiny__=9 -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -Werror=implicit-function-declaration -Xclang -isystem/emsdk-main/upstream/emscripten/cache/sysroot/include/SDL2 --sysroot=/emsdk-main/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -DUSE_CMAKE_CONFIG_H -D_IRR_STATIC_LIB_ -Dminetest_EXPORTS -I/data/build/minetest/src -I/data/minetest/src -I/data/install/include -I/data/minetest/lib/lua/src -I/data/minetest/lib/gmp -I/data/minetest/lib/jsoncpp -I/data/minetest/lib/bitop -I/data/minetest/src/script -I/data/install/include/freetype2 -I/emsdk-main/upstream/emscripten/system/include -I/data/minetest/lib/irrlichtmt/include -I/data/minetest/lib/irrlichtmt/source/Irrlicht -O2 -pthread -fexceptions -DNDEBUG -Wall -Wsign-compare -Wall -pipe -funroll-loops -O3 -fomit-frame-pointer -fno-math-errno -fno-trapping-math -ffinite-math-only -fno-signed-zeros -std=gnu++14 -c -matomics -mbulk-memory /data/minetest/src/network/address.cpp -o CMakeFiles/minetest.dir/network/address.cpp.o' failed (returned 1)
make[2]: *** [src/CMakeFiles/minetest.dir/build.make:1511: src/CMakeFiles/minetest.dir/network/address.cpp.o] Error 1
```

**Comment by paradust7** [comment]
Turns out the problem you encountered was a regression in emsdk. I encountered it when I updated my own emsdk. It should be fixed as of 9b654503fe8a725db069eae5e198505e3f28c230 !

You can add a call to `apply_patches.sh` to apply all the emsdk patches.

**Comment by paradust7** [comment]
@BuckarooBanzay FYI I added a Dockerfile, and a build action to keep it green:

https://github.com/paradust7/minetest-wasm/actions

I didn't include nginx because I don't really have a use case for it yet, and it would need https/ssl certificates to work correctly anyway (self-signed may work). Maybe in the future it could be useful for selenium tests.

Thanks for the help!

**Comment by BuckarooBanzay** [comment]
nice :+1: sorry for not following up on this, had other stuff to do :)

**Pull request closed without merging**
